[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["node_modules", "contracts/lib"]
solc = "0.8.24"
remappings = [
    "@fhevm/solidity/=node_modules/@fhevm/solidity/",
    "encrypted-types/=node_modules/encrypted-types/",
]

[rpc_endpoints]
zama_sepolia = "https://sepolia.fheoma.zama.xyz"