[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
solc = "0.8.27"

[fhe]
supportedNetworks = ["zama_fhevm", "zama_fhevm_sepolia"]

[rpc_env]
zama_fhevm_sepolia = "${ZAMA_FHEVM_RPC_URL}"

[etherscan]
zama_fhevm_sepolia = { key = "${ZAMA_FHEVM_API_KEY}" }

[private_keys]
default = "${DEPLOYER_PRIVATE_KEY}"