/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialPayrollInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addEmployee"
      | "confidentialProtocolId"
      | "depositFunds"
      | "fundPool"
      | "getAllEmployees"
      | "getBalance"
      | "getBonus"
      | "getEmployeeAt"
      | "getEmployeeCount"
      | "getSalary"
      | "isEmployee"
      | "owner"
      | "processPayroll"
      | "removeEmployee"
      | "setBonus"
      | "setSalary"
      | "totalCompensation"
      | "updateTotalCompensation"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BonusSet"
      | "EmployeeAdded"
      | "EmployeeRemoved"
      | "FundsDeposited"
      | "PayrollProcessed"
      | "SalarySet"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositFunds",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fundPool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllEmployees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBonus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployeeAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployeeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSalary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processPayroll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBonus",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSalary",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCompensation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateTotalCompensation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllEmployees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBonus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEmployeeAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmployeeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSalary", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isEmployee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processPayroll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBonus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setSalary", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalCompensation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTotalCompensation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace BonusSetEvent {
  export type InputTuple = [employee: AddressLike];
  export type OutputTuple = [employee: string];
  export interface OutputObject {
    employee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployeeAddedEvent {
  export type InputTuple = [employee: AddressLike];
  export type OutputTuple = [employee: string];
  export interface OutputObject {
    employee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployeeRemovedEvent {
  export type InputTuple = [employee: AddressLike];
  export type OutputTuple = [employee: string];
  export interface OutputObject {
    employee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsDepositedEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayrollProcessedEvent {
  export type InputTuple = [employeeCount: BigNumberish];
  export type OutputTuple = [employeeCount: bigint];
  export interface OutputObject {
    employeeCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalarySetEvent {
  export type InputTuple = [employee: AddressLike];
  export type OutputTuple = [employee: string];
  export interface OutputObject {
    employee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [employee: AddressLike, amount: BigNumberish];
  export type OutputTuple = [employee: string, amount: bigint];
  export interface OutputObject {
    employee: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialPayroll extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialPayroll;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialPayrollInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addEmployee: TypedContractMethod<
    [employee: AddressLike],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  depositFunds: TypedContractMethod<[], [void], "payable">;

  fundPool: TypedContractMethod<[], [bigint], "view">;

  getAllEmployees: TypedContractMethod<[], [string[]], "view">;

  getBalance: TypedContractMethod<[employee: AddressLike], [string], "view">;

  getBonus: TypedContractMethod<[employee: AddressLike], [string], "view">;

  getEmployeeAt: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getEmployeeCount: TypedContractMethod<[], [bigint], "view">;

  getSalary: TypedContractMethod<[employee: AddressLike], [string], "view">;

  isEmployee: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  processPayroll: TypedContractMethod<[], [void], "nonpayable">;

  removeEmployee: TypedContractMethod<
    [employee: AddressLike],
    [void],
    "nonpayable"
  >;

  setBonus: TypedContractMethod<
    [employee: AddressLike, encBonus: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  setSalary: TypedContractMethod<
    [employee: AddressLike, encSalary: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  totalCompensation: TypedContractMethod<[], [string], "view">;

  updateTotalCompensation: TypedContractMethod<[], [void], "nonpayable">;

  withdraw: TypedContractMethod<
    [amountCents: BigNumberish, ethAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addEmployee"
  ): TypedContractMethod<[employee: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositFunds"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "fundPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllEmployees"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[employee: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getBonus"
  ): TypedContractMethod<[employee: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEmployeeAt"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEmployeeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSalary"
  ): TypedContractMethod<[employee: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "isEmployee"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processPayroll"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeEmployee"
  ): TypedContractMethod<[employee: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBonus"
  ): TypedContractMethod<
    [employee: AddressLike, encBonus: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSalary"
  ): TypedContractMethod<
    [employee: AddressLike, encSalary: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalCompensation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateTotalCompensation"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [amountCents: BigNumberish, ethAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BonusSet"
  ): TypedContractEvent<
    BonusSetEvent.InputTuple,
    BonusSetEvent.OutputTuple,
    BonusSetEvent.OutputObject
  >;
  getEvent(
    key: "EmployeeAdded"
  ): TypedContractEvent<
    EmployeeAddedEvent.InputTuple,
    EmployeeAddedEvent.OutputTuple,
    EmployeeAddedEvent.OutputObject
  >;
  getEvent(
    key: "EmployeeRemoved"
  ): TypedContractEvent<
    EmployeeRemovedEvent.InputTuple,
    EmployeeRemovedEvent.OutputTuple,
    EmployeeRemovedEvent.OutputObject
  >;
  getEvent(
    key: "FundsDeposited"
  ): TypedContractEvent<
    FundsDepositedEvent.InputTuple,
    FundsDepositedEvent.OutputTuple,
    FundsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "PayrollProcessed"
  ): TypedContractEvent<
    PayrollProcessedEvent.InputTuple,
    PayrollProcessedEvent.OutputTuple,
    PayrollProcessedEvent.OutputObject
  >;
  getEvent(
    key: "SalarySet"
  ): TypedContractEvent<
    SalarySetEvent.InputTuple,
    SalarySetEvent.OutputTuple,
    SalarySetEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "BonusSet(address)": TypedContractEvent<
      BonusSetEvent.InputTuple,
      BonusSetEvent.OutputTuple,
      BonusSetEvent.OutputObject
    >;
    BonusSet: TypedContractEvent<
      BonusSetEvent.InputTuple,
      BonusSetEvent.OutputTuple,
      BonusSetEvent.OutputObject
    >;

    "EmployeeAdded(address)": TypedContractEvent<
      EmployeeAddedEvent.InputTuple,
      EmployeeAddedEvent.OutputTuple,
      EmployeeAddedEvent.OutputObject
    >;
    EmployeeAdded: TypedContractEvent<
      EmployeeAddedEvent.InputTuple,
      EmployeeAddedEvent.OutputTuple,
      EmployeeAddedEvent.OutputObject
    >;

    "EmployeeRemoved(address)": TypedContractEvent<
      EmployeeRemovedEvent.InputTuple,
      EmployeeRemovedEvent.OutputTuple,
      EmployeeRemovedEvent.OutputObject
    >;
    EmployeeRemoved: TypedContractEvent<
      EmployeeRemovedEvent.InputTuple,
      EmployeeRemovedEvent.OutputTuple,
      EmployeeRemovedEvent.OutputObject
    >;

    "FundsDeposited(address,uint256)": TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;
    FundsDeposited: TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;

    "PayrollProcessed(uint256)": TypedContractEvent<
      PayrollProcessedEvent.InputTuple,
      PayrollProcessedEvent.OutputTuple,
      PayrollProcessedEvent.OutputObject
    >;
    PayrollProcessed: TypedContractEvent<
      PayrollProcessedEvent.InputTuple,
      PayrollProcessedEvent.OutputTuple,
      PayrollProcessedEvent.OutputObject
    >;

    "SalarySet(address)": TypedContractEvent<
      SalarySetEvent.InputTuple,
      SalarySetEvent.OutputTuple,
      SalarySetEvent.OutputObject
    >;
    SalarySet: TypedContractEvent<
      SalarySetEvent.InputTuple,
      SalarySetEvent.OutputTuple,
      SalarySetEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
