/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialPayrollFHEInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addEmployee"
      | "getEmployee"
      | "getEmployeeCount"
      | "getEncryptedBonus"
      | "getEncryptedSalary"
      | "isEmployee"
      | "orgId"
      | "owner"
      | "processPayrollEncrypted"
      | "setEncryptedBonus"
      | "setEncryptedSalary"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BonusDistributedEncrypted"
      | "EmployeeAdded"
      | "PayrollProcessedEncrypted"
      | "SalarySetEncrypted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployeeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedBonus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedSalary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "orgId", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processPayrollEncrypted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setEncryptedBonus",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEncryptedSalary",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmployeeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedSalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isEmployee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orgId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processPayrollEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEncryptedBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEncryptedSalary",
    data: BytesLike
  ): Result;
}

export namespace BonusDistributedEncryptedEvent {
  export type InputTuple = [employee: AddressLike];
  export type OutputTuple = [employee: string];
  export interface OutputObject {
    employee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployeeAddedEvent {
  export type InputTuple = [employee: AddressLike];
  export type OutputTuple = [employee: string];
  export interface OutputObject {
    employee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayrollProcessedEncryptedEvent {
  export type InputTuple = [employeeCount: BigNumberish];
  export type OutputTuple = [employeeCount: bigint];
  export interface OutputObject {
    employeeCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalarySetEncryptedEvent {
  export type InputTuple = [employee: AddressLike];
  export type OutputTuple = [employee: string];
  export interface OutputObject {
    employee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialPayrollFHE extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialPayrollFHE;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialPayrollFHEInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addEmployee: TypedContractMethod<
    [employee: AddressLike],
    [void],
    "nonpayable"
  >;

  getEmployee: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getEmployeeCount: TypedContractMethod<[], [bigint], "view">;

  getEncryptedBonus: TypedContractMethod<
    [employee: AddressLike],
    [bigint],
    "view"
  >;

  getEncryptedSalary: TypedContractMethod<
    [employee: AddressLike],
    [bigint],
    "view"
  >;

  isEmployee: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  orgId: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  processPayrollEncrypted: TypedContractMethod<[], [bigint], "nonpayable">;

  setEncryptedBonus: TypedContractMethod<
    [employee: AddressLike, encryptedBonus: BigNumberish],
    [void],
    "nonpayable"
  >;

  setEncryptedSalary: TypedContractMethod<
    [employee: AddressLike, encryptedSalary: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addEmployee"
  ): TypedContractMethod<[employee: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEmployee"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEmployeeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedBonus"
  ): TypedContractMethod<[employee: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedSalary"
  ): TypedContractMethod<[employee: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isEmployee"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "orgId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processPayrollEncrypted"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "setEncryptedBonus"
  ): TypedContractMethod<
    [employee: AddressLike, encryptedBonus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEncryptedSalary"
  ): TypedContractMethod<
    [employee: AddressLike, encryptedSalary: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BonusDistributedEncrypted"
  ): TypedContractEvent<
    BonusDistributedEncryptedEvent.InputTuple,
    BonusDistributedEncryptedEvent.OutputTuple,
    BonusDistributedEncryptedEvent.OutputObject
  >;
  getEvent(
    key: "EmployeeAdded"
  ): TypedContractEvent<
    EmployeeAddedEvent.InputTuple,
    EmployeeAddedEvent.OutputTuple,
    EmployeeAddedEvent.OutputObject
  >;
  getEvent(
    key: "PayrollProcessedEncrypted"
  ): TypedContractEvent<
    PayrollProcessedEncryptedEvent.InputTuple,
    PayrollProcessedEncryptedEvent.OutputTuple,
    PayrollProcessedEncryptedEvent.OutputObject
  >;
  getEvent(
    key: "SalarySetEncrypted"
  ): TypedContractEvent<
    SalarySetEncryptedEvent.InputTuple,
    SalarySetEncryptedEvent.OutputTuple,
    SalarySetEncryptedEvent.OutputObject
  >;

  filters: {
    "BonusDistributedEncrypted(address)": TypedContractEvent<
      BonusDistributedEncryptedEvent.InputTuple,
      BonusDistributedEncryptedEvent.OutputTuple,
      BonusDistributedEncryptedEvent.OutputObject
    >;
    BonusDistributedEncrypted: TypedContractEvent<
      BonusDistributedEncryptedEvent.InputTuple,
      BonusDistributedEncryptedEvent.OutputTuple,
      BonusDistributedEncryptedEvent.OutputObject
    >;

    "EmployeeAdded(address)": TypedContractEvent<
      EmployeeAddedEvent.InputTuple,
      EmployeeAddedEvent.OutputTuple,
      EmployeeAddedEvent.OutputObject
    >;
    EmployeeAdded: TypedContractEvent<
      EmployeeAddedEvent.InputTuple,
      EmployeeAddedEvent.OutputTuple,
      EmployeeAddedEvent.OutputObject
    >;

    "PayrollProcessedEncrypted(uint256)": TypedContractEvent<
      PayrollProcessedEncryptedEvent.InputTuple,
      PayrollProcessedEncryptedEvent.OutputTuple,
      PayrollProcessedEncryptedEvent.OutputObject
    >;
    PayrollProcessedEncrypted: TypedContractEvent<
      PayrollProcessedEncryptedEvent.InputTuple,
      PayrollProcessedEncryptedEvent.OutputTuple,
      PayrollProcessedEncryptedEvent.OutputObject
    >;

    "SalarySetEncrypted(address)": TypedContractEvent<
      SalarySetEncryptedEvent.InputTuple,
      SalarySetEncryptedEvent.OutputTuple,
      SalarySetEncryptedEvent.OutputObject
    >;
    SalarySetEncrypted: TypedContractEvent<
      SalarySetEncryptedEvent.InputTuple,
      SalarySetEncryptedEvent.OutputTuple,
      SalarySetEncryptedEvent.OutputObject
    >;
  };
}
