/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialPayrollFHEInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addEmployee"
      | "canViewEmployeeData"
      | "confidentialProtocolId"
      | "depositFunds"
      | "fundPool"
      | "getAllEmployees"
      | "getEmployee"
      | "getEmployeeCount"
      | "getEncryptedBalance"
      | "getEncryptedBonus"
      | "getEncryptedSalary"
      | "getFundPool"
      | "grantAccess"
      | "isEmployee"
      | "orgId"
      | "owner"
      | "processPayrollEncrypted"
      | "removeEmployee"
      | "revokeAccess"
      | "setEncryptedBonus"
      | "setEncryptedSalary"
      | "withdrawSalary"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "AccessRevoked"
      | "BonusSet"
      | "EmployeeAdded"
      | "EmployeeRemoved"
      | "FundsDeposited"
      | "PayrollProcessed"
      | "SalarySet"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canViewEmployeeData",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositFunds",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fundPool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllEmployees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployeeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedBonus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedSalary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFundPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "orgId", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processPayrollEncrypted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEncryptedBonus",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEncryptedSalary",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawSalary",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canViewEmployeeData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllEmployees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmployeeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedSalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFundPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isEmployee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orgId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processPayrollEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEncryptedBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEncryptedSalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawSalary",
    data: BytesLike
  ): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [employee: AddressLike, viewer: AddressLike];
  export type OutputTuple = [employee: string, viewer: string];
  export interface OutputObject {
    employee: string;
    viewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRevokedEvent {
  export type InputTuple = [employee: AddressLike, viewer: AddressLike];
  export type OutputTuple = [employee: string, viewer: string];
  export interface OutputObject {
    employee: string;
    viewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BonusSetEvent {
  export type InputTuple = [employee: AddressLike];
  export type OutputTuple = [employee: string];
  export interface OutputObject {
    employee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployeeAddedEvent {
  export type InputTuple = [employee: AddressLike];
  export type OutputTuple = [employee: string];
  export interface OutputObject {
    employee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployeeRemovedEvent {
  export type InputTuple = [employee: AddressLike];
  export type OutputTuple = [employee: string];
  export interface OutputObject {
    employee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsDepositedEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayrollProcessedEvent {
  export type InputTuple = [employeeCount: BigNumberish];
  export type OutputTuple = [employeeCount: bigint];
  export interface OutputObject {
    employeeCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalarySetEvent {
  export type InputTuple = [employee: AddressLike];
  export type OutputTuple = [employee: string];
  export interface OutputObject {
    employee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [employee: AddressLike, amount: BigNumberish];
  export type OutputTuple = [employee: string, amount: bigint];
  export interface OutputObject {
    employee: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialPayrollFHE extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialPayrollFHE;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialPayrollFHEInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addEmployee: TypedContractMethod<
    [employee: AddressLike],
    [void],
    "nonpayable"
  >;

  canViewEmployeeData: TypedContractMethod<
    [employee: AddressLike, viewer: AddressLike],
    [boolean],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  depositFunds: TypedContractMethod<[], [void], "payable">;

  fundPool: TypedContractMethod<[], [bigint], "view">;

  getAllEmployees: TypedContractMethod<[], [string[]], "view">;

  getEmployee: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getEmployeeCount: TypedContractMethod<[], [bigint], "view">;

  getEncryptedBalance: TypedContractMethod<
    [employee: AddressLike],
    [string],
    "view"
  >;

  getEncryptedBonus: TypedContractMethod<
    [employee: AddressLike],
    [string],
    "view"
  >;

  getEncryptedSalary: TypedContractMethod<
    [employee: AddressLike],
    [string],
    "view"
  >;

  getFundPool: TypedContractMethod<[], [bigint], "view">;

  grantAccess: TypedContractMethod<[viewer: AddressLike], [void], "nonpayable">;

  isEmployee: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  orgId: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  processPayrollEncrypted: TypedContractMethod<[], [void], "nonpayable">;

  removeEmployee: TypedContractMethod<
    [employee: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeAccess: TypedContractMethod<
    [viewer: AddressLike],
    [void],
    "nonpayable"
  >;

  setEncryptedBonus: TypedContractMethod<
    [employee: AddressLike, encBonus: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  setEncryptedSalary: TypedContractMethod<
    [employee: AddressLike, encSalary: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  withdrawSalary: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addEmployee"
  ): TypedContractMethod<[employee: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canViewEmployeeData"
  ): TypedContractMethod<
    [employee: AddressLike, viewer: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositFunds"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "fundPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllEmployees"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getEmployee"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEmployeeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedBalance"
  ): TypedContractMethod<[employee: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedBonus"
  ): TypedContractMethod<[employee: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedSalary"
  ): TypedContractMethod<[employee: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getFundPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<[viewer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isEmployee"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "orgId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processPayrollEncrypted"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeEmployee"
  ): TypedContractMethod<[employee: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<[viewer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEncryptedBonus"
  ): TypedContractMethod<
    [employee: AddressLike, encBonus: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEncryptedSalary"
  ): TypedContractMethod<
    [employee: AddressLike, encSalary: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawSalary"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRevoked"
  ): TypedContractEvent<
    AccessRevokedEvent.InputTuple,
    AccessRevokedEvent.OutputTuple,
    AccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "BonusSet"
  ): TypedContractEvent<
    BonusSetEvent.InputTuple,
    BonusSetEvent.OutputTuple,
    BonusSetEvent.OutputObject
  >;
  getEvent(
    key: "EmployeeAdded"
  ): TypedContractEvent<
    EmployeeAddedEvent.InputTuple,
    EmployeeAddedEvent.OutputTuple,
    EmployeeAddedEvent.OutputObject
  >;
  getEvent(
    key: "EmployeeRemoved"
  ): TypedContractEvent<
    EmployeeRemovedEvent.InputTuple,
    EmployeeRemovedEvent.OutputTuple,
    EmployeeRemovedEvent.OutputObject
  >;
  getEvent(
    key: "FundsDeposited"
  ): TypedContractEvent<
    FundsDepositedEvent.InputTuple,
    FundsDepositedEvent.OutputTuple,
    FundsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "PayrollProcessed"
  ): TypedContractEvent<
    PayrollProcessedEvent.InputTuple,
    PayrollProcessedEvent.OutputTuple,
    PayrollProcessedEvent.OutputObject
  >;
  getEvent(
    key: "SalarySet"
  ): TypedContractEvent<
    SalarySetEvent.InputTuple,
    SalarySetEvent.OutputTuple,
    SalarySetEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "AccessGranted(address,address)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "AccessRevoked(address,address)": TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
    AccessRevoked: TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;

    "BonusSet(address)": TypedContractEvent<
      BonusSetEvent.InputTuple,
      BonusSetEvent.OutputTuple,
      BonusSetEvent.OutputObject
    >;
    BonusSet: TypedContractEvent<
      BonusSetEvent.InputTuple,
      BonusSetEvent.OutputTuple,
      BonusSetEvent.OutputObject
    >;

    "EmployeeAdded(address)": TypedContractEvent<
      EmployeeAddedEvent.InputTuple,
      EmployeeAddedEvent.OutputTuple,
      EmployeeAddedEvent.OutputObject
    >;
    EmployeeAdded: TypedContractEvent<
      EmployeeAddedEvent.InputTuple,
      EmployeeAddedEvent.OutputTuple,
      EmployeeAddedEvent.OutputObject
    >;

    "EmployeeRemoved(address)": TypedContractEvent<
      EmployeeRemovedEvent.InputTuple,
      EmployeeRemovedEvent.OutputTuple,
      EmployeeRemovedEvent.OutputObject
    >;
    EmployeeRemoved: TypedContractEvent<
      EmployeeRemovedEvent.InputTuple,
      EmployeeRemovedEvent.OutputTuple,
      EmployeeRemovedEvent.OutputObject
    >;

    "FundsDeposited(address,uint256)": TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;
    FundsDeposited: TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;

    "PayrollProcessed(uint256)": TypedContractEvent<
      PayrollProcessedEvent.InputTuple,
      PayrollProcessedEvent.OutputTuple,
      PayrollProcessedEvent.OutputObject
    >;
    PayrollProcessed: TypedContractEvent<
      PayrollProcessedEvent.InputTuple,
      PayrollProcessedEvent.OutputTuple,
      PayrollProcessedEvent.OutputObject
    >;

    "SalarySet(address)": TypedContractEvent<
      SalarySetEvent.InputTuple,
      SalarySetEvent.OutputTuple,
      SalarySetEvent.OutputObject
    >;
    SalarySet: TypedContractEvent<
      SalarySetEvent.InputTuple,
      SalarySetEvent.OutputTuple,
      SalarySetEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
