// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://deginpwtznmdwnnnbwsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlZ2lucHd0em5tZHdubm5id3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5Nzc3NjUsImV4cCI6MjA5MTU1Mzc2NX0.OBSnAAwkKbvLxkV0WDupUhcxQKXPH4tREi4i64kqsAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});